CC=g++
CFLAGS=-fPIC -Wall -Wextra -std=c++11 

DIR11=$(HOME)/programmi/c++11

INCLUDE=	-I./ 				
APPNAME=color
		
color=$(DIR11)/color/color.cpp
main=./main.cpp
SRCFILES=$(main) $(color) 


$(APPNAME) : $(SRCFILES)
	$(CC) $(CFLAGS) $(INCLUDE) $(SRCFILES) $(LIB) -o $(HOME)/bin/$(APPNAME)
	   
	   
		
		
		

